blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/sjoerdvink99/tableverse/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
